"""empty message

Revision ID: 118d09da4eb8
Revises: 21eb0ea97b3d
Create Date: 2020-02-28 13:30:01.596726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '118d09da4eb8'
down_revision = '21eb0ea97b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('time_updated', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('experiment_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.uuid'], name='results_experiment_id_fkey'),
    sa.PrimaryKeyConstraint('uuid', name='results_pkey')
    )
    # ### end Alembic commands ###
