"""empty message

Revision ID: 21eb0ea97b3d
Revises: 34f785803f50
Create Date: 2020-02-19 19:38:34.133426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21eb0ea97b3d'
down_revision = '34f785803f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'validation_result')
    op.drop_column('results', 'valid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('valid', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('results', sa.Column('validation_result', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
