"""empty message

Revision ID: 34f785803f50
Revises: ad324cf07a60
Create Date: 2020-02-19 19:25:01.181525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34f785803f50'
down_revision = 'ad324cf07a60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('experiments', 'blob',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    op.alter_column('experiments', 'blob_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('results', sa.Column('processed_by', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'processed_by')
    op.alter_column('experiments', 'blob_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('experiments', 'blob',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    op.drop_column('experiments', 'name')
    # ### end Alembic commands ###
