"""empty message

Revision ID: ad324cf07a60
Revises: b8bedc8f584e
Create Date: 2020-02-18 11:07:00.644730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad324cf07a60'
down_revision = 'b8bedc8f584e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('password_hash', sa.String(length=150), nullable=True))
    op.drop_constraint('teams_country_id_fkey', 'teams', type_='foreignkey')
    op.drop_column('teams', 'country_id')
    op.drop_table('countries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('country_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('teams_country_id_fkey', 'teams', 'countries', ['country_id'], ['uuid'])
    op.drop_column('teams', 'password_hash')
    op.create_table('countries',
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name='countries_pkey')
    )
    # ### end Alembic commands ###
