"""init

Revision ID: b8bedc8f584e
Revises: 
Create Date: 2020-02-18 09:29:45.637432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8bedc8f584e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'countries',
        sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('time_created',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=True), sa.Column('name',
                                            sa.String(),
                                            nullable=False),
        sa.PrimaryKeyConstraint('uuid'))
    op.create_table(
        'parts', sa.Column('igem_id', sa.String(), nullable=False),
        sa.Column('time_created',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=True), sa.PrimaryKeyConstraint('igem_id'))
    op.create_table(
        'teams',
        sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('time_created',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=True), sa.Column('name',
                                            sa.String(),
                                            nullable=False),
        sa.Column('country_id', postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['country_id'],
            ['countries.uuid'],
        ), sa.PrimaryKeyConstraint('uuid'))
    op.create_table(
        'experiments',
        sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('time_created',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=True),
        sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
        sa.Column('protocol_type', sa.String(), nullable=True),
        sa.Column('blob_hash', sa.String(), nullable=False),
        sa.Column('blob', sa.LargeBinary(), nullable=False),
        sa.Column('team_id', postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ['team_id'],
            ['teams.uuid'],
        ), sa.PrimaryKeyConstraint('uuid'), sa.UniqueConstraint('blob_hash'))
    op.create_table(
        'parts_experiments',
        sa.Column('parts_uuid', sa.String(), nullable=False),
        sa.Column('experiments_uuid',
                  postgresql.UUID(as_uuid=True),
                  nullable=True),
        sa.ForeignKeyConstraint(
            ['experiments_uuid'],
            ['experiments.uuid'],
        ), sa.ForeignKeyConstraint(
            ['parts_uuid'],
            ['parts.igem_id'],
        ), sa.PrimaryKeyConstraint('parts_uuid', 'experiments_uuid'))
    op.create_table(
        'results',
        sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('time_created',
                  sa.DateTime(timezone=True),
                  server_default=sa.text('now()'),
                  nullable=True),
        sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
        sa.Column('experiment_id', postgresql.UUID(), nullable=False),
        sa.Column('validation_result', sa.String(), nullable=False),
        sa.Column('valid', sa.Boolean(), nullable=False),
        sa.Column('result', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ['experiment_id'],
            ['experiments.uuid'],
        ), sa.PrimaryKeyConstraint('uuid'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.drop_table('parts_experiments')
    op.drop_table('experiments')
    op.drop_table('teams')
    op.drop_table('parts')
    op.drop_table('countries')
    # ### end Alembic commands ###
